platform: linux

image_resource:
  type: docker-image
  source:
    repository: alpine
    tag: "latest"

inputs:
- name: source

outputs:
- name: tag

run:
  path: source/concourse/tasks/create-tag/task.sh