---
infrastructure:
  infrastructure_service_name: cpa-aws
  repo_name: TeliaSoneraNorge/TeliaSoneraNorge/cpa-aws
  deploy_key_name: cpa-aws-deploy-key
  project_name: telia-no-cpa
  slack_channel: cpa-deploys
microservices:
  - service_name: cpa-provision-service
    repo_name: TeliaSoneraNorge/cpa-provision-service
    deploy_key_name: cpa-provision-service-deploy-key
    docker_image_repo: 358107645737.dkr.ecr.eu-west-1.amazonaws.com/cpa-provision-service
    project_type: java_gradle
  - service_name: cpa-settlement-service
    repo_name: TeliaSoneraNorge/cpa-settlement-service
    deploy_key_name: cpa-settlement-service-deploy-key
    docker_image_repo: 358107645737.dkr.ecr.eu-west-1.amazonaws.com/cpa-settlement-service
    project_type: java_gradle
  - service_name: cpa-callback-service
    repo_name: TeliaSoneraNorge/cpa-callback-service
    deploy_key_name: cpa-callback-service-deploy-key
    docker_image_repo: 358107645737.dkr.ecr.eu-west-1.amazonaws.com/cpa-callback-service
    project_type: java_gradle
  - service_name: cpa-api-service
    repo_name: TeliaSoneraNorge/cpa-api-service
    deploy_key_name: cpa-api-service-deploy-key
    docker_image_repo: 358107645737.dkr.ecr.eu-west-1.amazonaws.com/cpa-api-service
    project_type: java_gradle
  - service_name: cpa-smpp-service
    repo_name: TeliaSoneraNorge/cpa-smpp-service
    deploy_key_name: cpa-smpp-service-deploy-key
    docker_image_repo: 358107645737.dkr.ecr.eu-west-1.amazonaws.com/cpa-smpp-service
    project_type: java_gradle
  - service_name: cpa-charge-service
    repo_name: TeliaSoneraNorge/cpa-charge-service
    deploy_key_name: cpa-charge-service-deploy-key
    docker_image_repo: 358107645737.dkr.ecr.eu-west-1.amazonaws.com/cpa-charge-service
    project_type: java_gradle
  - service_name: cpa-message-service
    repo_name: TeliaSoneraNorge/cpa-message-service
    deploy_key_name: cpa-provision-service-message-key
    docker_image_repo: 358107645737.dkr.ecr.eu-west-1.amazonaws.com/cpa-message-service
    project_type: java_gradle
  - service_name: cpa-deliver-service
    repo_name: TeliaSoneraNorge/cpa-deliver-service
    deploy_key_name: cpa-provision-service-deliver-key
    docker_image_repo: 358107645737.dkr.ecr.eu-west-1.amazonaws.com/cpa-deliver-service
    project_type: java_gradle

