---
meta:
  webhook: &webhook-config
    check_every: 24h
    webhook_token: <webhook-token>
  slack: &slack-config
    username: 'concourse'
    channel: '<slack-channel>'
    icon_url: 'http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png'
  failure: &slack-failure
    put: notify
    params:
      <<: *slack-config
      text: |
        Build failed:
        https://concourse.common-services.telia.io/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME

groups:
  - name: Master
    jobs:
<groups-master-jobs>
  - name: PR
    jobs:
<groups-pr-jobs>

jobs:
<jobs-jobs>
- name: deploy-dev
  serial: true
  plan:
  - aggregate:
<jobs-deploy-dev-triggers>
  - aggregate:
<bumping-development>
  - put: version
    params:
      repository: bumped-version/
      rebase: true
  - task: deploy
    attempts: 2
    file: common-tasks/terraform/0.11.3.yml
    input_mapping: { source: bumped-source }
    params:
      command: apply
      directories: terraform/development
      access_key: ((<project-name>-dev-access-key))
      secret_key: ((<project-name>-dev-secret-key))
      session_token: ((<project-name>-dev-session-token))
    on_failure: *slack-failure

- name: integration
  plan:
  - aggregate:
<jobs-integration-triggers>
  - aggregate:
    - task: integration-tests
      file: <infrastruture-service-name>/.ci/tasks/integration-tests/task.yml
      input_mapping: { source: <infrastruture-service-name> }
      on_failure: *slack-failure

- name: deploy-stage
  serial: true
  plan:
  - aggregate:
<jobs-deploy-stage-triggers>
  - aggregate:
<bumping-staging>
  - put: version
    params:
      repository: bumped-version/
      rebase: true
  - task: deploy
    attempts: 2
    file: common-tasks/terraform/0.11.3.yml
    input_mapping: { source: bumped-source }
    params:
      command: apply
      directories: terraform/staging
      access_key: ((<project-name>-stage-access-key))
      secret_key: ((<project-name>-stage-secret-key))
      session_token: ((<project-name>-stage-session-token))
    on_failure: *slack-failure

- name: deploy-prod
  serial: true
  plan:
  - aggregate:
<jobs-deploy-prod-triggers>
  - aggregate:
<bumping-production>
  - put: version
    params:
      repository: bumped-version/
      rebase: true
  - task: deploy
    attempts: 2
    file: common-tasks/terraform/0.11.3.yml
    input_mapping: { source: bumped-source }
    params:
      command: apply
      directories: terraform/production
      access_key: ((<project-name>-prod-access-key))
      secret_key: ((<project-name>-prod-secret-key))
      session_token: ((<project-name>-prod-session-token))
    on_failure: *slack-failure

resource_types:
  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource
      tag: latest
  - name: pull-request
    type: docker-image
    source:
      repository: jtarchie/pr

resources:
<resources>