platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven
    tag: alpine

inputs:
  - name: source
  - name: pipeline-repo

caches:
  - path: .m2/

outputs:
  - name: build-artefacts

run:
  path: privacy-aws/concourse/tasks/maven-deploy/task.sh